use std::{cmp::Ordering, collections::{BTreeMap,HashMap,HashSet}, sync::Arc, time::Duration};
use futures::{stream,StreamExt};
use tokio::{sync::{watch,Mutex},task::JoinHandle};
use veilid_core::RecordKey;
use crate::{
    dht_module::DHTModule,
    gossip::{GossipFingerprint,GossipIndexToken,GossipManager,GossipRecord,GossipSearchQuery,GossipTokenMatchMode,GossipTokenPolarity,GossipTokenProbe},
    types::{current_timestamp,LEXICAL_LIBRARY_ADVERTISEMENT_LOCATION},
    user_auth::{UserAuth,UserSession},
    user_dht::MainDhtRuntime,
    walk_task::WalkTask,
};
use super::{
    sketches::{EntityFingerprint,HllSketch,SamplePoint},
    storage::{build_membership_filter,decode_advertisements,decode_manifest,decode_page,encode_advertisements,encode_manifest,encode_page,find_advertisement,membership_filter_maybe_contains,page_for_phrase,page_for_word,page_payload},
    tokenize::{compare_words,language_minhash,topic_minhash,tokenize_text,Lexeme},
    types::*,
};

pub const LEXICAL_MANAGER_STORE_KEY:&str="lexical_library_manager_state";
#[derive(Debug)]pub enum LexicalError{InvalidInput(String),Storage(String),Dht(String),Gossip(String),LibraryNotFound}
impl std::fmt::Display for LexicalError{fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{match self{Self::InvalidInput(m)=>write!(f,"invalid lexical input: {m}"),Self::Storage(m)=>write!(f,"lexical storage error: {m}"),Self::Dht(m)=>write!(f,"lexical DHT error: {m}"),Self::Gossip(m)=>write!(f,"lexical gossip error: {m}"),Self::LibraryNotFound=>write!(f,"lexical library was not found")}}}
impl std::error::Error for LexicalError{}

#[derive(Debug,Clone,PartialEq,Eq,Hash)]struct LibraryKey{application_id:String,library_name:String}
impl LibraryKey{fn new(a:&str,l:&str)->Self{Self{application_id:a.to_string(),library_name:l.to_string()}}}
struct LibraryState{
    application_id:String,library_name:String,library_id:LibraryId,package_index:usize,library_dht:RecordKey,
    manifest:LexicalLibraryManifest,words:HashMap<WordId,LexicalWordEntry>,phrases:HashMap<(String,PhraseId),PhraseEvidence>,
    universe:BTreeMap<String,UniverseLayerEvidence>,object_profiles:HashMap<EntityFingerprint,ObjectProfileAccumulator>,
    dirty_pages:HashSet<u16>,dirty_gossip:HashSet<(String,WordId)>,dirty_phrases:HashSet<(String,PhraseId)>,durable_words:HashSet<WordId>,
    manifest_dirty:bool,loaded:bool,last_flush_at:u64,
}
impl LibraryState{fn advertisement(&self)->LexicalLibraryAdvertisement{LexicalLibraryAdvertisement{library_id:self.library_id,application_id:self.application_id.clone(),library_name:self.library_name.clone(),library_dht:self.library_dht.to_string(),generation:self.manifest.generation,updated_at:self.manifest.updated_at,word_count:self.manifest.word_count,current_epoch:self.manifest.current_epoch,active_window_days:self.manifest.active_window_days,node_coordinate:self.manifest.node_coordinate,retention_radius:self.manifest.retention_radius,membership_filter:self.manifest.membership_filter}}}
#[derive(Default)]struct ManagerState{libraries:HashMap<LibraryKey,LibraryState>}

#[derive(Clone)]pub struct LexicalLibraryManager{
    state:Arc<Mutex<ManagerState>>,creation_lock:Arc<Mutex<()>>,dht_module:DHTModule,auth:Arc<UserAuth>,session:Arc<UserSession>,main_runtime:MainDhtRuntime,gossip:GossipManager,walk_task:Option<WalkTask>,main_dht:String,node_coordinate:[u8;32],stop_tx:watch::Sender<bool>,background_task:Arc<Mutex<Option<JoinHandle<()>>>>,
}

impl LexicalLibraryManager{
    pub async fn load(auth:Arc<UserAuth>,session:Arc<UserSession>,dht_module:DHTModule,main_runtime:MainDhtRuntime,gossip:GossipManager,walk_task:Option<WalkTask>,main_dht:String)->Result<Self,LexicalError>{
        let node_coordinate=node_coordinate(&main_dht);let(stop_tx,_)=watch::channel(false);let manager=Self{state:Arc::new(Mutex::new(ManagerState::default())),creation_lock:Arc::new(Mutex::new(())),dht_module,auth,session,main_runtime,gossip,walk_task,main_dht,node_coordinate,stop_tx,background_task:Arc::new(Mutex::new(None))};manager.restore_descriptors().await?;manager.publish_advertisements().await?;Ok(manager)
    }
    pub async fn start_background(&self){let mut slot=self.background_task.lock().await;if slot.is_some(){return;}let manager=self.clone();let mut shutdown=self.stop_tx.subscribe();*slot=Some(tokio::spawn(async move{let mut ticker=tokio::time::interval(Duration::from_secs(LEXICAL_BACKGROUND_TICK_SECS));ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);loop{tokio::select!{changed=shutdown.changed()=>{if changed.is_err()||*shutdown.borrow(){break;}},_=ticker.tick()=>{manager.rollover_and_prune().await;if let Err(e)=manager.publish_dirty_gossip().await{crate::teprintln!("[lexical] gossip flush failed: {e}");}if let Err(e)=manager.flush_due_libraries(false).await{crate::teprintln!("[lexical] DHT flush failed: {e}");}}}}}));}
    pub async fn shutdown(&self)->Result<(),LexicalError>{let _=self.stop_tx.send(true);if let Some(task)=self.background_task.lock().await.take(){let _=task.await;}self.flush_due_libraries(true).await?;Ok(())}
    pub fn compare_terms(&self,left:&str,right:&str)->WordSimilarity{compare_words(left,right)}

    pub async fn observe(&self,application_id:&str,request:LexicalObserveRequest)->Result<LexicalObserveResult,LexicalError>{
        validate_observe_request(application_id,&request)?;self.gossip.activate_application(application_id).await.map_err(|e|LexicalError::Gossip(e.to_string()))?;self.ensure_library(application_id,&request.library_name).await?;
        let tokenized=tokenize_text(request.text.as_deref().unwrap_or(""),&request.pretokenized_terms);let current_epoch=epoch_for(current_timestamp());let entity=entity_fingerprint(&request.object_id);let entity_hash=stable_hash64(b"VK-LEX-ENTITY-HLL-V1\0",request.object_id.as_bytes());let sample_hash=stable_hash64(b"VK-LEX-SAMPLE-V1\0",request.object_id.as_bytes());
        let mut mention_counts:HashMap<WordId,u16>=HashMap::new();for lex in &tokenized.words{let c=mention_counts.entry(lex.word_id).or_insert(0);*c=c.saturating_add(1);}let unique_word_ids:Vec<WordId>=mention_counts.keys().copied().collect();
        let key=LibraryKey::new(application_id,&request.library_name);
        let(overall_topic,overall_language,posting_words,result)={
            let mut state=self.state.lock().await;let library=state.libraries.get_mut(&key).ok_or(LexicalError::LibraryNotFound)?;if !library.loaded{return Err(LexicalError::Storage("library was not loaded after activation".into()));}
            let common_ids=identify_common_words(library,&request.layer,current_epoch,&unique_word_ids);let current_topic=topic_minhash(&unique_word_ids);let current_language=language_minhash(&unique_word_ids,&mention_counts,&common_ids);
            let accumulator=library.object_profiles.entry(entity).or_default();if request.generation>=accumulator.generation{accumulator.generation=request.generation;accumulator.fields.insert(request.field_id.clone(),unique_word_ids.clone());accumulator.field_layers.insert(request.field_id.clone(),request.layer.clone());}
            let all_words:Vec<WordId>=accumulator.fields.values().flat_map(|v|v.iter().copied()).collect();let overall_topic=if all_words.is_empty(){current_topic.clone()}else{topic_minhash(&all_words)};let overall_language=if all_words.is_empty(){current_language.clone()}else{let mut counts=HashMap::new();for w in &all_words{let c=counts.entry(*w).or_insert(0u16);*c=c.saturating_add(1);}let commons=identify_common_words(library,&request.layer,current_epoch,&all_words);language_minhash(&all_words,&counts,&commons)};
            library.universe.entry(request.layer.clone()).or_insert_with(||UniverseLayerEvidence::new(request.layer.clone())).daily.entry(current_epoch).or_insert_with(HllSketch::universe).add_hash(entity_hash);
            let mut touched=HashSet::new();for(position,lexeme)in tokenized.words.iter().enumerate(){let mentions=mention_counts.get(&lexeme.word_id).copied().unwrap_or(1);let entry=library.words.entry(lexeme.word_id).or_insert_with(||new_word_entry(lexeme,current_epoch));update_word_observation(entry,&request.layer,current_epoch,entity,entity_hash,sample_hash,request.generation,mentions,occurrence_hash(&request.object_id,request.generation,&request.field_id,position,&lexeme.word_id),&overall_topic,&overall_language);touched.insert(lexeme.word_id);}
            let mut associations_observed=0usize;for position in 0..tokenized.words.len(){let word=tokenized.words[position].word_id;for distance in 1..=LEXICAL_ASSOCIATION_RADIUS{if let Some(p)=position.checked_sub(distance){let other=tokenized.words[p].word_id;if other!=word{if let Some(entry)=library.words.get_mut(&word){update_neighbor(&mut entry.previous,other,distance,entity_hash,pair_occurrence_hash(&request.object_id,request.generation,&request.field_id,p,position,&other,&word),current_epoch);associations_observed+=1;}}}let n=position+distance;if n<tokenized.words.len(){let other=tokenized.words[n].word_id;if other!=word{if let Some(entry)=library.words.get_mut(&word){update_neighbor(&mut entry.following,other,distance,entity_hash,pair_occurrence_hash(&request.object_id,request.generation,&request.field_id,position,n,&word,&other),current_epoch);associations_observed+=1;}}}}}
            let mut phrases_considered=0usize;for(pair_position,pair)in tokenized.words.windows(2).enumerate(){if pair[0].word_id==pair[1].word_id{continue;}phrases_considered+=1;let phrase_id=derive_phrase_id(&[pair[0].word_id,pair[1].word_id]);let pkey=(request.layer.clone(),phrase_id);let evidence=library.phrases.entry(pkey.clone()).or_insert_with(||PhraseEvidence::new(phrase_id,request.layer.clone(),vec![pair[0].word_id,pair[1].word_id],current_epoch));let ep=evidence.daily.entry(current_epoch).or_insert_with(||EpochEvidence::new(current_epoch));ep.distinct_objects.add_hash(entity_hash);ep.distinct_occurrences.add_hash(pair_occurrence_hash(&request.object_id,request.generation,&request.field_id,pair_position,pair_position+1,&pair[0].word_id,&pair[1].word_id));evidence.left_occurrences.entry(current_epoch).or_insert_with(HllSketch::word).add_hash(occurrence_hash(&request.object_id,request.generation,&request.field_id,pair_position,&pair[0].word_id));evidence.last_seen_epoch=current_epoch;evidence.revision=evidence.revision.saturating_add(1);evidence.promoted=phrase_should_promote(evidence,current_epoch);library.dirty_phrases.insert(pkey);library.dirty_pages.insert(page_for_phrase(&phrase_id));}
            let subword_layer=format!("__subword/{}",request.layer);let mut unique_subwords=HashSet::new();for lexeme in tokenized.subwords.iter().take(512){if !unique_subwords.insert(lexeme.word_id){continue;}let entry=library.words.entry(lexeme.word_id).or_insert_with(||new_word_entry(lexeme,current_epoch));update_word_observation(entry,&subword_layer,current_epoch,entity,entity_hash,sample_hash,request.generation,1,stable_hash64(b"VK-LEX-SUBWORD-OBS-V1\0",&lexeme.word_id.0),&overall_topic,&overall_language);touched.insert(lexeme.word_id);}
            for word_id in &touched{library.dirty_pages.insert(page_for_word(word_id));if !word_is_subword_only(library.words.get(word_id),&request.layer){library.dirty_gossip.insert((request.layer.clone(),*word_id));}}
            library.manifest.current_epoch=current_epoch;library.manifest_dirty=true;prune_library_epochs(library,current_epoch);enforce_memory_retention(library,self.node_coordinate);
            let mut posting:Vec<(WordId,f64)>=unique_word_ids.iter().filter_map(|w|library.words.get(w).map(|entry|(*w,calculate_word_stats(entry,&library.universe,&request.layer,current_epoch,LEXICAL_ACTIVE_WINDOW_DAYS).search_utility))).collect();posting.sort_by(|a,b|b.1.partial_cmp(&a.1).unwrap_or(Ordering::Equal));posting.truncate(crate::gossip::GOSSIP_MAX_INDEX_TOKENS);let posting_words=posting.into_iter().map(|x|x.0).collect::<Vec<_>>();
            (overall_topic.clone(),overall_language.clone(),posting_words,LexicalObserveResult{library_id:library.library_id,words_observed:tokenized.words.len(),unique_words:unique_word_ids.len(),subword_tokens:tokenized.subwords.len(),associations_observed,phrases_considered,topic_minhash:overall_topic,language_minhash:overall_language,current_epoch})
        };
        if request.publish_posting_hint&&!posting_words.is_empty(){let record=GossipRecord{namespace:LEXICAL_GOSSIP_NAMESPACE_POSTING.into(),object_id:request.object_id.clone(),generation:request.generation,origin_main_dht:self.main_dht.clone(),published_at:current_timestamp(),expires_at:current_timestamp().saturating_add(LEXICAL_GOSSIP_TTL_SECS),authoritative_pointer:request.authoritative_pointer.clone(),fingerprints:vec![GossipFingerprint{channel:"lexical/topic".into(),algorithm:"minhash16".into(),version:1,bytes:encode_minhash_bytes(&overall_topic)},GossipFingerprint{channel:"lexical/language".into(),algorithm:"minhash16".into(),version:1,bytes:encode_minhash_bytes(&overall_language)}],index_tokens:posting_words.iter().map(word_gossip_token).collect(),custom_payload:Vec::new(),flags:0,withdrawn:false};if let Err(e)=self.gossip.publish_system_record(application_id,record).await{crate::teprintln!("[lexical] posting hint publish failed: {e}");}}
        Ok(result)
    }

    pub async fn withdraw_object(&self,application_id:&str,library_name:&str,object_id:&str,generation:Option<u64>)->Result<(),LexicalError>{self.ensure_library(application_id,library_name).await?;{let mut state=self.state.lock().await;if let Some(l)=state.libraries.get_mut(&LibraryKey::new(application_id,library_name)){l.object_profiles.remove(&entity_fingerprint(object_id));}}match self.gossip.withdraw_system(application_id,LEXICAL_GOSSIP_NAMESPACE_POSTING,object_id,generation).await{Ok(_)|Err(crate::gossip::GossipError::ObjectNotFound)=>Ok(()),Err(e)=>Err(LexicalError::Gossip(e.to_string()))}}
    pub async fn search(&self,application_id:&str,library_name:&str,layer:&str,terms:&[String],window_days:u16,query_network:bool)->Result<LexicalSearchResult,LexicalError>{
        if terms.is_empty()||terms.len()>LEXICAL_MAX_SEARCH_TERMS{return Err(LexicalError::InvalidInput(format!("search requires 1..={} terms",LEXICAL_MAX_SEARCH_TERMS)));}
        self.gossip.activate_application(application_id).await.map_err(|e|LexicalError::Gossip(e.to_string()))?;self.ensure_library(application_id,library_name).await?;
        let lexemes:Vec<Lexeme>=terms.iter().filter_map(|t|super::tokenize::lexeme(t)).collect();if lexemes.is_empty(){return Err(LexicalError::InvalidInput("no searchable terms remained after normalization".into()));}let word_ids:Vec<WordId>=lexemes.iter().map(|l|l.word_id).collect();let window_days=window_days.clamp(1,LEXICAL_DAILY_EPOCHS_TO_KEEP);let key=LibraryKey::new(application_id,library_name);
        let mut aggregate_words=Vec::new();let mut dht_libraries_consulted=0usize;let mut gossip_peers_contacted=0usize;
        for word_id in &word_ids{
            let(local_entry,local_universe)={let state=self.state.lock().await;let library=state.libraries.get(&key).ok_or(LexicalError::LibraryNotFound)?;(library.words.get(word_id).cloned(),library.universe.clone())};
            let mut merged_entry=local_entry;let mut merged_universe=local_universe;let mut sources=usize::from(merged_entry.is_some());
            if query_network{
                // Live gossip is a fast, untrusted view. We may use it in this
                // query, but never persist its df sketch by itself because it
                // does not carry the matching observation-universe N.
                let query=GossipSearchQuery{namespace:LEXICAL_GOSSIP_NAMESPACE_WORD.into(),probes:Vec::new(),token_probes:vec![GossipTokenProbe{tokens:vec![word_gossip_token(word_id)],polarity:GossipTokenPolarity::Required,match_mode:GossipTokenMatchMode::All,weight:1}],limit:16,min_score_milli:None,include_withdrawn:false};
                let(_,contacted,hits)=self.gossip.search(application_id,query,true,350).await.map_err(|e|LexicalError::Gossip(e.to_string()))?;gossip_peers_contacted+=contacted;for hit in hits{if let Ok(summary)=bincode::deserialize::<LexicalGossipWordSummary>(&hit.record.custom_payload){if summary.word_id==*word_id&&summary.layer==layer{merge_gossip_summary_into_entry(&mut merged_entry,&summary);sources+=1;}}}
                let remote=self.read_remote_word_evidence(application_id,library_name,word_id).await;dht_libraries_consulted+=remote.len();for evidence in remote{merge_word_entry(&mut merged_entry,&evidence.word);merge_universe_maps(&mut merged_universe,&evidence.universe);sources+=1;self.merge_learned_word(application_id,library_name,evidence.word,&evidence.universe).await?;}
            }
            aggregate_words.push(if let Some(entry)=merged_entry{word_view(&entry,&merged_universe,layer,window_days,sources)}else{empty_word_view(*word_id,layer,window_days)});
        }
        let posting_query=GossipSearchQuery{namespace:LEXICAL_GOSSIP_NAMESPACE_POSTING.into(),probes:Vec::new(),token_probes:vec![GossipTokenProbe{tokens:word_ids.iter().map(word_gossip_token).collect(),polarity:GossipTokenPolarity::Required,match_mode:GossipTokenMatchMode::All,weight:1}],limit:LEXICAL_MAX_CANDIDATE_HINTS.min(crate::gossip::GOSSIP_MAX_QUERY_RESULTS),min_score_milli:None,include_withdrawn:false};
        let(_,contacted,hits)=self.gossip.search(application_id,posting_query,query_network,350).await.map_err(|e|LexicalError::Gossip(e.to_string()))?;gossip_peers_contacted+=contacted;let candidates=hits.into_iter().map(|hit|LexicalCandidateHint{object_id:hit.record.object_id,generation:hit.record.generation,origin_main_dht:hit.record.origin_main_dht,authoritative_pointer:hit.record.authoritative_pointer,matched_words:hit.matched_index_tokens,verification:format!("{:?}",hit.verification)}).collect();
        Ok(LexicalSearchResult{library_id:derive_library_id(application_id,library_name),terms:word_ids,words:aggregate_words,candidates,gossip_peers_contacted,dht_libraries_consulted})
    }

    pub async fn association_metrics(&self,application_id:&str,library_name:&str,layer:&str,left:&str,right:&str,window_days:u16)->Result<AssociationMetrics,LexicalError>{self.ensure_library(application_id,library_name).await?;let left=super::tokenize::lexeme(left).ok_or_else(||LexicalError::InvalidInput("left term is empty".into()))?;let right=super::tokenize::lexeme(right).ok_or_else(||LexicalError::InvalidInput("right term is empty".into()))?;let state=self.state.lock().await;let library=state.libraries.get(&LibraryKey::new(application_id,library_name)).ok_or(LexicalError::LibraryNotFound)?;let current=epoch_for(current_timestamp());let window=window_days.clamp(1,LEXICAL_DAILY_EPOCHS_TO_KEEP);let minimum=current.saturating_sub(window.saturating_sub(1)as u64);let le=library.words.get(&left.word_id).ok_or(LexicalError::LibraryNotFound)?;let re=library.words.get(&right.word_id).ok_or(LexicalError::LibraryNotFound)?;let ls=calculate_word_stats(le,&library.universe,layer,current,window);let rs=calculate_word_stats(re,&library.universe,layer,current,window);let joint=le.following.iter().find(|n|n.word_id==right.word_id).map(|n|super::sketches::union_hll(4,n.daily.range(minimum..=current).map(|(_,e)|&e.distinct_objects)).estimate()).unwrap_or(0.0);let conditional=if ls.estimated_objects_containing_word>0.0{(joint/ls.estimated_objects_containing_word).clamp(0.0,1.0)}else{0.0};let n=ls.estimated_universe_objects.max(rs.estimated_universe_objects);let pmi=if n>0.0&&ls.estimated_objects_containing_word>0.0&&rs.estimated_objects_containing_word>0.0&&joint>0.0{let p_ab=joint/n;let p_a=ls.estimated_objects_containing_word/n;let p_b=rs.estimated_objects_containing_word/n;Some((p_ab/(p_a*p_b)).ln())}else{None};Ok(AssociationMetrics{left:left.word_id,right:right.word_id,layer:layer.to_string(),window_days:window,estimated_joint_objects:joint,conditional_right_given_left:conditional,pmi,confidence:support_confidence(joint)})}

    pub async fn stats(&self,application_id:&str,library_name:&str)->Result<LexicalLibraryStats,LexicalError>{self.ensure_library(application_id,library_name).await?;let state=self.state.lock().await;let l=state.libraries.get(&LibraryKey::new(application_id,library_name)).ok_or(LexicalError::LibraryNotFound)?;Ok(LexicalLibraryStats{application_id:application_id.to_string(),library_name:library_name.to_string(),library_id:l.library_id,library_dht:l.library_dht.to_string(),generation:l.manifest.generation,word_count:l.words.len(),phrase_count:l.phrases.len(),dirty_pages:l.dirty_pages.len(),dirty_gossip_words:l.dirty_gossip.len(),dirty_phrases:l.dirty_phrases.len(),current_epoch:l.manifest.current_epoch})}

    async fn restore_descriptors(&self)->Result<(),LexicalError>{let stored=self.auth.read_user_encrypted::<StoredLexicalManagerState>(&self.session,LEXICAL_MANAGER_STORE_KEY).map_err(|e|LexicalError::Storage(e.to_string()))?.unwrap_or_default();if stored.version!=0&&stored.version!=LEXICAL_MODULE_VERSION{return Ok(());}let mut restored=Vec::new();for descriptor in stored.libraries{let Some(package)=self.dht_module.get_dht_info(descriptor.package_index).await else{continue;};let dht_key=package.dht_record.key().clone();let manifest=match self.dht_module.read_from_dht(descriptor.package_index,LEXICAL_LIBRARY_MANIFEST_SUBKEY,false).await{Ok(bytes)=>match decode_manifest(&bytes){Ok(m)if m.library_id==descriptor.library_id=>m,_=>continue},Err(_)=>continue};restored.push((descriptor,dht_key,manifest));}let mut state=self.state.lock().await;for(descriptor,dht_key,manifest)in restored{let universe=manifest.universe_layers.iter().cloned().map(|e|(e.layer.clone(),e)).collect();state.libraries.insert(LibraryKey::new(&descriptor.application_id,&descriptor.library_name),LibraryState{application_id:descriptor.application_id,library_name:descriptor.library_name,library_id:descriptor.library_id,package_index:descriptor.package_index,library_dht:dht_key,manifest,words:HashMap::new(),phrases:HashMap::new(),universe,object_profiles:HashMap::new(),dirty_pages:HashSet::new(),dirty_gossip:HashSet::new(),dirty_phrases:HashSet::new(),durable_words:HashSet::new(),manifest_dirty:false,loaded:false,last_flush_at:current_timestamp()});}Ok(())}

    async fn ensure_library(&self,application_id:&str,library_name:&str)->Result<(),LexicalError>{
        validate_library_name(library_name)?;let key=LibraryKey::new(application_id,library_name);
        let existing={let state=self.state.lock().await;state.libraries.get(&key).map(|l|(l.loaded,l.package_index,l.manifest.populated_pages.clone()))};
        if let Some((true,_,_))=existing{return Ok(());}if let Some((false,package,pages))=existing{let loaded=self.load_library_pages(package,&pages).await?;let mut state=self.state.lock().await;if let Some(l)=state.libraries.get_mut(&key){for page in loaded{for word in page.words{l.durable_words.insert(word.word_id);l.words.insert(word.word_id,word);}for phrase in page.phrases{l.phrases.insert((phrase.layer.clone(),phrase.phrase_id),phrase);}}l.loaded=true;}return Ok(());}
        let _guard=self.creation_lock.lock().await;
        // Another task may have created it while we waited.
        if self.state.lock().await.libraries.contains_key(&key){drop(_guard);return self.ensure_existing_after_wait(&key).await;}
        if self.state.lock().await.libraries.len()>=LEXICAL_MAX_LOCAL_LIBRARIES{return Err(LexicalError::Storage("too many local lexical libraries".into()));}
        let library_id=derive_library_id(application_id,library_name);let package_index=self.dht_module.create_dht(format!("lexical_{}",&library_id.hex()[..12]),vec![LEXICAL_LIBRARY_TOTAL_SUBKEYS]).await.map_err(|e|LexicalError::Dht(format!("could not create lexical DHT: {e:?}")))?;let library_dht=self.dht_module.package_id_to_key(package_index).await.map_err(|e|LexicalError::Dht(format!("could not obtain lexical DHT key: {e:?}")))?;let now=current_timestamp();let epoch=epoch_for(now);let manifest=LexicalLibraryManifest{record_version:LEXICAL_LIBRARY_RECORD_VERSION,library_id,application_id:application_id.to_string(),library_name:library_name.to_string(),generation:1,updated_at:now,current_epoch:epoch,epoch_secs:LEXICAL_EPOCH_SECS,active_window_days:LEXICAL_ACTIVE_WINDOW_DAYS,word_count:0,phrase_count:0,populated_pages:Vec::new(),node_coordinate:self.node_coordinate,retention_radius:[0xFF;32],membership_filter:[0u8;LEXICAL_MEMBERSHIP_FILTER_BYTES],universe_layers:Vec::new()};self.dht_module.write_to_dht(package_index,LEXICAL_LIBRARY_MANIFEST_SUBKEY,encode_manifest(&manifest).map_err(LexicalError::Storage)?).await.map_err(|e|LexicalError::Dht(format!("could not initialize lexical manifest: {e:?}")))?;
        {let mut state=self.state.lock().await;state.libraries.insert(key,LibraryState{application_id:application_id.to_string(),library_name:library_name.to_string(),library_id,package_index,library_dht,manifest,words:HashMap::new(),phrases:HashMap::new(),universe:BTreeMap::new(),object_profiles:HashMap::new(),dirty_pages:HashSet::new(),dirty_gossip:HashSet::new(),dirty_phrases:HashSet::new(),durable_words:HashSet::new(),manifest_dirty:false,loaded:true,last_flush_at:now});}
        self.persist_descriptors_and_dht_snapshot().await?;self.publish_advertisements().await?;Ok(())
    }
    async fn ensure_existing_after_wait(&self,key:&LibraryKey)->Result<(),LexicalError>{let existing={let state=self.state.lock().await;state.libraries.get(key).map(|l|(l.loaded,l.package_index,l.manifest.populated_pages.clone()))};if let Some((true,_,_))=existing{return Ok(());}if let Some((false,pkg,pages))=existing{let loaded=self.load_library_pages(pkg,&pages).await?;let mut state=self.state.lock().await;if let Some(l)=state.libraries.get_mut(key){for page in loaded{for w in page.words{l.durable_words.insert(w.word_id);l.words.insert(w.word_id,w);}for p in page.phrases{l.phrases.insert((p.layer.clone(),p.phrase_id),p);}}l.loaded=true;}return Ok(());}Err(LexicalError::LibraryNotFound)}
    async fn load_library_pages(&self,package_index:usize,pages:&[u16])->Result<Vec<LexicalLibraryPage>,LexicalError>{let reads=stream::iter(pages.iter().copied()).map(|page|{let dht=self.dht_module.clone();async move{let bytes=dht.read_from_dht(package_index,page as u32,false).await.map_err(|e|LexicalError::Dht(format!("could not read lexical page {page}: {e:?}")))?;decode_page(&bytes).map_err(LexicalError::Storage)}}).buffer_unordered(LEXICAL_REMOTE_READ_CONCURRENCY);tokio::pin!(reads);let mut result=Vec::new();while let Some(page)=reads.next().await{result.push(page?);}Ok(result)}
    async fn persist_descriptors_and_dht_snapshot(&self)->Result<(),LexicalError>{let descriptors={let state=self.state.lock().await;state.libraries.values().map(|l|StoredLibraryDescriptor{application_id:l.application_id.clone(),library_name:l.library_name.clone(),library_id:l.library_id,package_index:l.package_index}).collect()};let stored=StoredLexicalManagerState{version:LEXICAL_MODULE_VERSION,libraries:descriptors};self.auth.write_user_encrypted(&self.session,LEXICAL_MANAGER_STORE_KEY,&stored).map_err(|e|LexicalError::Storage(e.to_string()))?;let snapshot=self.dht_module.export_snapshot().await;crate::user_dht::persist_dht_snapshot(&self.auth,&self.session,&snapshot).map_err(|e|LexicalError::Storage(e.to_string()))?;Ok(())}
    async fn publish_advertisements(&self)->Result<(),LexicalError>{let libraries={let state=self.state.lock().await;state.libraries.values().map(LibraryState::advertisement).collect()};let set=LexicalLibraryAdvertisementSet{record_version:LEXICAL_ADVERTISEMENT_RECORD_VERSION,updated_at:current_timestamp(),libraries};self.main_runtime.publish_lexical_library_advertisements(encode_advertisements(&set).map_err(LexicalError::Storage)?).await.map_err(|e|LexicalError::Dht(e.to_string()))?;Ok(())}
    async fn flush_due_libraries(&self,force:bool)->Result<(),LexicalError>{let keys={let state=self.state.lock().await;state.libraries.keys().cloned().collect::<Vec<_>>()};let mut due_keys=Vec::new();for key in keys{let due={let state=self.state.lock().await;let Some(l)=state.libraries.get(&key)else{continue;};l.loaded&&(!l.dirty_pages.is_empty()||l.manifest_dirty)&&(force||current_timestamp().saturating_sub(l.last_flush_at)>=LEXICAL_DHT_FLUSH_SECS)};if due{due_keys.push(key);}}if due_keys.is_empty(){return Ok(());}let flushes=stream::iter(due_keys).map(|key|{let manager=self.clone();async move{manager.flush_library(&key).await}}).buffer_unordered(4);tokio::pin!(flushes);while let Some(result)=flushes.next().await{result?;}self.publish_advertisements().await?;Ok(())}
    async fn flush_library(&self,key:&LibraryKey)->Result<(),LexicalError>{
        let plan={let mut state=self.state.lock().await;let l=state.libraries.get_mut(key).ok_or(LexicalError::LibraryNotFound)?;let mut ranked:Vec<(WordId,[u8;32])>=l.words.keys().map(|w|(*w,xor_distance(&w.0,&self.node_coordinate))).collect();ranked.sort_by(|a,b|a.1.cmp(&b.1));ranked.truncate(LEXICAL_MAX_WORDS_DURABLE);let mut target:HashSet<WordId>=ranked.iter().map(|x|x.0).collect();for word in l.durable_words.symmetric_difference(&target){l.dirty_pages.insert(page_for_word(word));}
            let generation=l.manifest.generation.saturating_add(1).max(1);let dirty_pages=l.dirty_pages.clone();let mut pages=Vec::new();for page in dirty_pages.iter().copied(){let mut words:Vec<LexicalWordEntry>=target.iter().filter(|w|page_for_word(w)==page).filter_map(|w|l.words.get(w).cloned()).collect();words.sort_by_key(|w|xor_distance(&w.word_id.0,&self.node_coordinate));let phrases:Vec<PhraseEvidence>=l.phrases.values().filter(|p|p.promoted&&page_for_phrase(&p.phrase_id)==page&&p.components.first().map_or(false,|w|target.contains(w))).cloned().collect();loop{let payload=page_payload(l.library_id,generation,page,words.clone(),phrases.clone());match encode_page(&payload){Ok(bytes)=>{pages.push((page,bytes));break},Err(_)if!words.is_empty()=>{if let Some(removed)=words.pop(){target.remove(&removed.word_id);}},Err(e)=>return Err(LexicalError::Storage(e))}}}
            let mut populated_pages:Vec<u16>=target.iter().map(page_for_word).collect::<HashSet<_>>().into_iter().collect();for p in l.phrases.values().filter(|p|p.promoted){if p.components.first().map_or(false,|w|target.contains(w)){populated_pages.push(page_for_phrase(&p.phrase_id));}}populated_pages.sort_unstable();populated_pages.dedup();let membership_filter=build_membership_filter(target.iter());let retention_radius=ranked.get(target.len().saturating_sub(1)).map(|(_,d)|*d).unwrap_or([0xFF;32]);let manifest=LexicalLibraryManifest{record_version:LEXICAL_LIBRARY_RECORD_VERSION,library_id:l.library_id,application_id:l.application_id.clone(),library_name:l.library_name.clone(),generation,updated_at:current_timestamp(),current_epoch:epoch_for(current_timestamp()),epoch_secs:LEXICAL_EPOCH_SECS,active_window_days:LEXICAL_ACTIVE_WINDOW_DAYS,word_count:target.len()as u32,phrase_count:l.phrases.values().filter(|p|p.promoted).count()as u32,populated_pages,node_coordinate:self.node_coordinate,retention_radius,membership_filter,universe_layers:l.universe.values().cloned().collect()};FlushPlan{package_index:l.package_index,generation,pages,manifest,target_words:target,dirty_pages}}
        ;let package_index=plan.package_index;{let writes=stream::iter(plan.pages.iter().cloned()).map(|(page,bytes)|{let dht=self.dht_module.clone();async move{dht.write_to_dht(package_index,page as u32,bytes).await.map_err(|e|LexicalError::Dht(format!("lexical page {page} write failed: {e:?}")))?;Ok::<(),LexicalError>(())}}).buffer_unordered(8);tokio::pin!(writes);while let Some(r)=writes.next().await{r?;}}
        self.dht_module.write_to_dht(plan.package_index,LEXICAL_LIBRARY_MANIFEST_SUBKEY,encode_manifest(&plan.manifest).map_err(LexicalError::Storage)?).await.map_err(|e|LexicalError::Dht(format!("lexical manifest commit failed: {e:?}")))?;{let mut state=self.state.lock().await;if let Some(l)=state.libraries.get_mut(key){if plan.generation>=l.manifest.generation{l.manifest=plan.manifest;l.durable_words=plan.target_words;for p in plan.dirty_pages{l.dirty_pages.remove(&p);}l.manifest_dirty=false;l.last_flush_at=current_timestamp();}}}Ok(())
    }

    async fn publish_dirty_gossip(&self)->Result<(),LexicalError>{let(jobs,phrase_jobs)={let mut state=self.state.lock().await;let mut jobs=Vec::new();let mut phrase_jobs=Vec::new();for l in state.libraries.values_mut(){let selected=l.dirty_gossip.iter().take(LEXICAL_GOSSIP_DIRTY_WORDS_PER_TICK).cloned().collect::<Vec<_>>();for(layer,word_id)in selected{l.dirty_gossip.remove(&(layer.clone(),word_id));if let Some(word)=l.words.get(&word_id){if let Some(summary)=gossip_summary(l.library_id,word,&layer,l.manifest.current_epoch){jobs.push((l.application_id.clone(),l.library_dht.to_string(),word.revision,summary));}}}let selectedp=l.dirty_phrases.iter().take(LEXICAL_GOSSIP_DIRTY_PHRASES_PER_TICK).cloned().collect::<Vec<_>>();for(layer,pid)in selectedp{l.dirty_phrases.remove(&(layer.clone(),pid));if let Some(p)=l.phrases.get(&(layer.clone(),pid)){if let Some(summary)=phrase_gossip_summary(l.library_id,p,l.manifest.current_epoch){phrase_jobs.push((l.application_id.clone(),l.library_dht.to_string(),p.revision,summary));}}}}(jobs,phrase_jobs)};
        for(app,pointer,generation,summary)in jobs{let payload=bincode::serialize(&summary).map_err(|e|LexicalError::Storage(e.to_string()))?;if payload.len()>crate::gossip::GOSSIP_MAX_CUSTOM_PAYLOAD_BYTES{continue;}let record=GossipRecord{namespace:LEXICAL_GOSSIP_NAMESPACE_WORD.into(),object_id:format!("{}:{}:{}",summary.library_id.hex(),summary.layer,summary.word_id.hex()),generation,origin_main_dht:self.main_dht.clone(),published_at:current_timestamp(),expires_at:current_timestamp().saturating_add(LEXICAL_GOSSIP_TTL_SECS),authoritative_pointer:Some(pointer),fingerprints:Vec::new(),index_tokens:vec![word_gossip_token(&summary.word_id)],custom_payload:payload,flags:0,withdrawn:false};let _=self.gossip.publish_system_record(&app,record).await;}
        for(app,pointer,generation,summary)in phrase_jobs{let payload=bincode::serialize(&summary).map_err(|e|LexicalError::Storage(e.to_string()))?;if payload.len()>crate::gossip::GOSSIP_MAX_CUSTOM_PAYLOAD_BYTES{continue;}let record=GossipRecord{namespace:LEXICAL_GOSSIP_NAMESPACE_PHRASE.into(),object_id:format!("{}:{}:{}",summary.library_id.hex(),summary.layer,summary.phrase_id.hex()),generation,origin_main_dht:self.main_dht.clone(),published_at:current_timestamp(),expires_at:current_timestamp().saturating_add(LEXICAL_GOSSIP_TTL_SECS),authoritative_pointer:Some(pointer),fingerprints:Vec::new(),index_tokens:summary.components.iter().map(word_gossip_token).collect(),custom_payload:payload,flags:0,withdrawn:false};let _=self.gossip.publish_system_record(&app,record).await;}Ok(())}

    async fn merge_learned_word(&self,application_id:&str,library_name:&str,entry:LexicalWordEntry,universe:&BTreeMap<String,UniverseLayerEvidence>)->Result<(),LexicalError>{let mut state=self.state.lock().await;let l=state.libraries.get_mut(&LibraryKey::new(application_id,library_name)).ok_or(LexicalError::LibraryNotFound)?;let id=entry.word_id;if let Some(existing)=l.words.get_mut(&id){let mut target=Some(existing.clone());merge_word_entry(&mut target,&entry);*existing=target.unwrap();}else{l.words.insert(id,entry);}merge_universe_maps(&mut l.universe,universe);l.dirty_pages.insert(page_for_word(&id));l.manifest_dirty=true;enforce_memory_retention(l,self.node_coordinate);Ok(())}
    async fn read_remote_word_evidence(&self,application_id:&str,library_name:&str,word_id:&WordId)->Vec<RemoteWordEvidence>{let Some(walk_task)=&self.walk_task else{return Vec::new();};let library_id=derive_library_id(application_id,library_name);let mut peers=if application_id==LEXICAL_TEST_APPLICATION_ID{walk_task.get_internal_list_copy().await.entries.into_iter().map(|e|e.their_address).collect::<Vec<_>>()}else{walk_task.active_app_nodes(application_id).await};peers.retain(|p|p.to_string()!=self.main_dht);peers.sort_by_key(|p|xor_distance(&word_id.0,&node_coordinate(&p.to_string())));peers.truncate(LEXICAL_REMOTE_LIBRARY_FANOUT);let reads=stream::iter(peers).map(|peer|{let dht=self.dht_module.clone();let app=application_id.to_string();let word=*word_id;async move{read_remote_word(&dht,peer,&app,library_id,word).await}}).buffer_unordered(LEXICAL_REMOTE_READ_CONCURRENCY);tokio::pin!(reads);let mut result=Vec::new();while let Some(item)=reads.next().await{if let Ok(Some(e))=item{result.push(e);}}result}
    async fn rollover_and_prune(&self){let current=epoch_for(current_timestamp());let mut state=self.state.lock().await;for l in state.libraries.values_mut().filter(|l|l.loaded){if l.manifest.current_epoch!=current{l.manifest.current_epoch=current;l.manifest_dirty=true;}prune_library_epochs(l,current);}}
}

struct FlushPlan{package_index:usize,generation:u64,pages:Vec<(u16,Vec<u8>)>,manifest:LexicalLibraryManifest,target_words:HashSet<WordId>,dirty_pages:HashSet<u16>}
struct RemoteWordEvidence{word:LexicalWordEntry,universe:BTreeMap<String,UniverseLayerEvidence>}

async fn read_remote_word(dht:&DHTModule,peer_main_dht:RecordKey,application_id:&str,library_id:LibraryId,word_id:WordId)->Result<Option<RemoteWordEvidence>,LexicalError>{let ad_bytes=dht.read_foreign_subkey(peer_main_dht,LEXICAL_LIBRARY_ADVERTISEMENT_LOCATION,true).await.map_err(|e|LexicalError::Dht(format!("peer lexical ad read failed: {e:?}")))?;let ads=decode_advertisements(&ad_bytes).map_err(LexicalError::Storage)?;let Some(ad)=find_advertisement(&ads,application_id,library_id)else{return Ok(None);};if !membership_filter_maybe_contains(&ad.membership_filter,&word_id){return Ok(None);}let library_key:RecordKey=ad.library_dht.parse().map_err(|e|LexicalError::Dht(format!("invalid lexical DHT: {e:?}")))?;let page=page_for_word(&word_id)as u32;let values=dht.read_foreign_subkeys(library_key,vec![LEXICAL_LIBRARY_MANIFEST_SUBKEY,page],true).await.map_err(|e|LexicalError::Dht(format!("remote lexical page read failed: {e:?}")))?;let mut manifest=None;let mut page_value=None;for(location,value)in values{let Ok(bytes)=value else{continue;};if location==LEXICAL_LIBRARY_MANIFEST_SUBKEY{manifest=decode_manifest(&bytes).ok();}else if location==page{page_value=decode_page(&bytes).ok();}}let(Some(manifest),Some(page_value))=(manifest,page_value)else{return Ok(None);};if manifest.library_id!=library_id||page_value.library_id!=library_id{return Ok(None);}let Some(word)=page_value.words.into_iter().find(|w|w.word_id==word_id)else{return Ok(None);};let universe=manifest.universe_layers.into_iter().map(|e|(e.layer.clone(),e)).collect();Ok(Some(RemoteWordEvidence{word,universe}))}
fn new_word_entry(lexeme:&Lexeme,epoch:u64)->LexicalWordEntry{LexicalWordEntry{word_id:lexeme.word_id,word_id_version:LEXICAL_WORD_ID_VERSION,canonicalization_version:LEXICAL_CANONICALIZATION_VERSION,script:lexeme.script.clone(),comparison:lexeme.comparison.clone(),layers:BTreeMap::new(),previous:Vec::new(),following:Vec::new(),context_exemplars:Vec::new(),language_exemplars:Vec::new(),first_seen_epoch:epoch,last_seen_epoch:epoch,revision:1}}
#[allow(clippy::too_many_arguments)]fn update_word_observation(entry:&mut LexicalWordEntry,layer:&str,epoch:u64,entity:EntityFingerprint,entity_hash:u64,sample_hash:u64,generation:u64,mentions:u16,occurrence_hash:u64,topic:&[u16],language:&[u16]){let layer=entry.layers.entry(layer.to_string()).or_insert_with(||LayerEvidence::new(layer.to_string()));let evidence=layer.daily.entry(epoch).or_insert_with(||EpochEvidence::new(epoch));evidence.distinct_objects.add_hash(entity_hash);evidence.distinct_occurrences.add_hash(occurrence_hash);layer.sample.upsert(SamplePoint{entity,sample_hash,generation,mentions,last_seen_epoch:epoch,topic_minhash:topic.to_vec(),language_minhash:language.to_vec()});push_exemplar(&mut entry.context_exemplars,topic,LEXICAL_MAX_MINHASH_EXEMPLARS);push_exemplar(&mut entry.language_exemplars,language,LEXICAL_MAX_MINHASH_EXEMPLARS);entry.last_seen_epoch=entry.last_seen_epoch.max(epoch);entry.revision=entry.revision.saturating_add(1);}
fn update_neighbor(neighbors:&mut Vec<NeighborEvidence>,other:WordId,distance:usize,entity_hash:u64,occurrence_hash:u64,epoch:u64){let index=if let Some(i)=neighbors.iter().position(|n|n.word_id==other){i}else{neighbors.push(NeighborEvidence::new(other));neighbors.len()-1};let neighbor=&mut neighbors[index];let ep=neighbor.daily.entry(epoch).or_insert_with(||NeighborEpochEvidence::new(epoch));if let Some(s)=ep.distance_occurrences.get_mut(distance.saturating_sub(1)){s.add_hash(occurrence_hash);}ep.distinct_objects.add_hash(entity_hash);neighbor.last_seen_epoch=neighbor.last_seen_epoch.max(epoch);neighbors.sort_by(|a,b|b.estimated_distinct_objects_all().partial_cmp(&a.estimated_distinct_objects_all()).unwrap_or(Ordering::Equal));neighbors.truncate(LEXICAL_MAX_NEIGHBORS_PER_DIRECTION);}
fn push_exemplar(target:&mut Vec<Vec<u16>>,value:&[u16],limit:usize){if value.is_empty()||target.iter().any(|x|x==value){return;}target.push(value.to_vec());if target.len()>limit{target.remove(0);}}
fn identify_common_words(library:&LibraryState,layer:&str,current:u64,ids:&[WordId])->HashSet<WordId>{ids.iter().filter_map(|id|{let e=library.words.get(id)?;let s=calculate_word_stats(e,&library.universe,layer,current,LEXICAL_ACTIVE_WINDOW_DAYS);(s.estimated_objects_containing_word>=10.0&&(s.prevalence>=0.15||s.rarity_normalized<=0.20)).then_some(*id)}).collect()}
fn calculate_word_stats(entry:&LexicalWordEntry,universe:&BTreeMap<String,UniverseLayerEvidence>,layer:&str,current:u64,window:u16)->LexicalWordStats{let minimum=current.saturating_sub(window.saturating_sub(1)as u64);let word_union=super::sketches::union_hll(6,entry.layers.get(layer).into_iter().flat_map(|l|l.daily.range(minimum..=current).map(|(_,e)|&e.distinct_objects)));let df=word_union.estimate();let universe_union=super::sketches::union_hll(10,universe.get(layer).into_iter().flat_map(|u|u.daily.range(minimum..=current).map(|(_,s)|s)));let n=universe_union.estimate();let prevalence=if n>0.0{(df/n).clamp(0.0,1.0)}else{0.0};let rarity_idf=if n>0.0{((n+1.0)/(df+1.0)).ln().max(0.0)}else{0.0};let rarity_normalized=1.0-(-rarity_idf).exp();let specificity=neighbor_specificity(entry,minimum,current);let evidence_confidence=support_confidence(df);let search_utility=rarity_normalized*specificity*evidence_confidence;let mention_statistics=entry.layers.get(layer).map(|l|l.sample.mention_statistics(minimum)).unwrap_or_default();LexicalWordStats{window_days:window,estimated_universe_objects:n,estimated_objects_containing_word:df,prevalence,rarity_idf,rarity_normalized,specificity,evidence_confidence,search_utility,mention_statistics}}
fn neighbor_specificity(entry:&LexicalWordEntry,minimum:u64,current:u64)->f64{let mut weights:Vec<f64>=entry.previous.iter().chain(&entry.following).map(|n|super::sketches::union_hll(4,n.daily.range(minimum..=current).map(|(_,e)|&e.distinct_objects)).estimate()).filter(|v|*v>0.0).collect();weights.sort_by(|a,b|b.partial_cmp(a).unwrap_or(Ordering::Equal));weights.truncate(32);if weights.len()<=1{return 1.0;}let total: f64=weights.iter().sum();if total<=0.0{return 0.0;}let entropy=weights.iter().map(|w|{let p=*w/total;if p>0.0{-p*p.ln()}else{0.0}}).sum::<f64>();let maximum=(weights.len()as f64).ln();if maximum<=0.0{1.0}else{(1.0-entropy/maximum).clamp(0.0,1.0)}}
fn support_confidence(support:f64)->f64{if support<=0.0{0.0}else{(1.0-(-support/25.0).exp()).clamp(0.0,1.0)}}
fn word_view(entry:&LexicalWordEntry,universe:&BTreeMap<String,UniverseLayerEvidence>,layer:&str,window:u16,sources:usize)->LexicalWordView{let current=epoch_for(current_timestamp());let minimum=current.saturating_sub(window.saturating_sub(1)as u64);let stats=calculate_word_stats(entry,universe,layer,current,window);let occurrence_total=entry.layers.get(layer).map(|l|super::sketches::union_hll(6,l.daily.range(minimum..=current).map(|(_,e)|&e.distinct_occurrences)).estimate()).unwrap_or(0.0);let mut neighbors=Vec::new();for(direction,list)in[("previous",&entry.previous),("following",&entry.following)]{for neighbor in list.iter().take(16){let mut best_distance=1usize;let mut best=0.0;for distance in 1..=LEXICAL_ASSOCIATION_RADIUS{let estimate=neighbor.estimated_occurrences_at(distance,minimum,current);if estimate>best{best=estimate;best_distance=distance;}}let objects=super::sketches::union_hll(4,neighbor.daily.range(minimum..=current).map(|(_,e)|&e.distinct_objects)).estimate();let conditional=if occurrence_total>0.0{(best/occurrence_total).clamp(0.0,1.0)}else{0.0};neighbors.push(LexicalNeighborStat{word_id:neighbor.word_id,direction:direction.into(),distance:best_distance as u8,estimated_occurrences:best,estimated_distinct_objects:objects,conditional_probability:conditional,confidence:support_confidence(objects)});}}neighbors.sort_by(|a,b|(b.conditional_probability*b.confidence).partial_cmp(&(a.conditional_probability*a.confidence)).unwrap_or(Ordering::Equal));neighbors.truncate(24);LexicalWordView{word_id:entry.word_id,layer:layer.into(),stats,script:entry.script.clone(),neighbors,context_exemplars:entry.context_exemplars.clone(),language_exemplars:entry.language_exemplars.clone(),sources_consulted:sources}}
fn empty_word_view(word_id:WordId,layer:&str,window:u16)->LexicalWordView{LexicalWordView{word_id,layer:layer.into(),stats:LexicalWordStats{window_days:window,estimated_universe_objects:0.0,estimated_objects_containing_word:0.0,prevalence:0.0,rarity_idf:0.0,rarity_normalized:0.0,specificity:0.0,evidence_confidence:0.0,search_utility:0.0,mention_statistics:Default::default()},script:Default::default(),neighbors:Vec::new(),context_exemplars:Vec::new(),language_exemplars:Vec::new(),sources_consulted:0}}

fn gossip_summary(library_id:LibraryId,entry:&LexicalWordEntry,layer:&str,epoch:u64)->Option<LexicalGossipWordSummary>{let layer_evidence=entry.layers.get(layer)?;let evidence=layer_evidence.daily.get(&epoch)?;let mut neighbors=Vec::new();for(direction,list)in[(0u8,&entry.previous),(1u8,&entry.following)]{for neighbor in list.iter().take(LEXICAL_GOSSIP_MAX_NEIGHBORS){let ep=neighbor.daily.get(&epoch)?;let(distance_index,occurrence)=ep.distance_occurrences.iter().enumerate().max_by(|(_,a),(_,b)|a.estimate().partial_cmp(&b.estimate()).unwrap_or(Ordering::Equal))?;neighbors.push(LexicalGossipNeighbor{word_id:neighbor.word_id,direction,distance:(distance_index+1)as u8,occurrence_sketch:occurrence.clone(),object_sketch:ep.distinct_objects.clone()});}}Some(LexicalGossipWordSummary{version:LEXICAL_MODULE_VERSION,library_id,layer:layer.into(),word_id:entry.word_id,epoch,distinct_objects:evidence.distinct_objects.clone(),distinct_occurrences:evidence.distinct_occurrences.clone(),neighbors,script:entry.script.clone(),context_exemplar:entry.context_exemplars.last().cloned().unwrap_or_default(),language_exemplar:entry.language_exemplars.last().cloned().unwrap_or_default()})}
fn phrase_gossip_summary(library_id:LibraryId,phrase:&PhraseEvidence,epoch:u64)->Option<LexicalGossipPhraseSummary>{let evidence=phrase.daily.get(&epoch)?;let left=phrase.left_occurrences.get(&epoch)?;Some(LexicalGossipPhraseSummary{version:LEXICAL_MODULE_VERSION,library_id,layer:phrase.layer.clone(),phrase_id:phrase.phrase_id,components:phrase.components.clone(),epoch,distinct_objects:evidence.distinct_objects.clone(),distinct_occurrences:evidence.distinct_occurrences.clone(),left_occurrences:left.clone()})}
fn merge_gossip_summary_into_entry(target:&mut Option<LexicalWordEntry>,summary:&LexicalGossipWordSummary){let mut incoming=target.take().unwrap_or_else(||LexicalWordEntry{word_id:summary.word_id,word_id_version:LEXICAL_WORD_ID_VERSION,canonicalization_version:LEXICAL_CANONICALIZATION_VERSION,script:summary.script.clone(),comparison:WordComparisonKeys{accent_fold_hash:[0;16],transliteration_hash:[0;16],visual_fold_hash:[0;16]},layers:BTreeMap::new(),previous:Vec::new(),following:Vec::new(),context_exemplars:Vec::new(),language_exemplars:Vec::new(),first_seen_epoch:summary.epoch,last_seen_epoch:summary.epoch,revision:1});let layer=incoming.layers.entry(summary.layer.clone()).or_insert_with(||LayerEvidence::new(summary.layer.clone()));let evidence=layer.daily.entry(summary.epoch).or_insert_with(||EpochEvidence::new(summary.epoch));let _=evidence.distinct_objects.merge(&summary.distinct_objects);let _=evidence.distinct_occurrences.merge(&summary.distinct_occurrences);for neighbor in &summary.neighbors{let list=if neighbor.direction==0{&mut incoming.previous}else{&mut incoming.following};let index=if let Some(i)=list.iter().position(|n|n.word_id==neighbor.word_id){i}else{list.push(NeighborEvidence::new(neighbor.word_id));list.len()-1};let existing=&mut list[index];let ep=existing.daily.entry(summary.epoch).or_insert_with(||NeighborEpochEvidence::new(summary.epoch));if let Some(s)=ep.distance_occurrences.get_mut(neighbor.distance.saturating_sub(1)as usize){let _=s.merge(&neighbor.occurrence_sketch);}let _=ep.distinct_objects.merge(&neighbor.object_sketch);existing.last_seen_epoch=existing.last_seen_epoch.max(summary.epoch);}push_exemplar(&mut incoming.context_exemplars,&summary.context_exemplar,LEXICAL_MAX_MINHASH_EXEMPLARS);push_exemplar(&mut incoming.language_exemplars,&summary.language_exemplar,LEXICAL_MAX_MINHASH_EXEMPLARS);incoming.last_seen_epoch=incoming.last_seen_epoch.max(summary.epoch);*target=Some(incoming)}
fn merge_word_entry(target:&mut Option<LexicalWordEntry>,incoming:&LexicalWordEntry){if target.is_none(){*target=Some(incoming.clone());return;}let target=target.as_mut().unwrap();for(layer_name,source)in &incoming.layers{let layer=target.layers.entry(layer_name.clone()).or_insert_with(||LayerEvidence::new(layer_name.clone()));for(epoch_id,src)in &source.daily{layer.daily.entry(*epoch_id).or_insert_with(||EpochEvidence::new(*epoch_id)).merge(src);}layer.sample.merge(&source.sample);}merge_neighbor_lists(&mut target.previous,&incoming.previous);merge_neighbor_lists(&mut target.following,&incoming.following);for e in &incoming.context_exemplars{push_exemplar(&mut target.context_exemplars,e,LEXICAL_MAX_MINHASH_EXEMPLARS);}for e in &incoming.language_exemplars{push_exemplar(&mut target.language_exemplars,e,LEXICAL_MAX_MINHASH_EXEMPLARS);}target.first_seen_epoch=target.first_seen_epoch.min(incoming.first_seen_epoch);target.last_seen_epoch=target.last_seen_epoch.max(incoming.last_seen_epoch);target.revision=target.revision.max(incoming.revision)}
fn merge_neighbor_lists(target:&mut Vec<NeighborEvidence>,incoming:&[NeighborEvidence]){for source in incoming{if let Some(existing)=target.iter_mut().find(|e|e.word_id==source.word_id){existing.merge(source)}else{target.push(source.clone())}}target.sort_by(|a,b|b.estimated_distinct_objects_all().partial_cmp(&a.estimated_distinct_objects_all()).unwrap_or(Ordering::Equal));target.truncate(LEXICAL_MAX_NEIGHBORS_PER_DIRECTION)}
fn merge_universe_maps(target:&mut BTreeMap<String,UniverseLayerEvidence>,incoming:&BTreeMap<String,UniverseLayerEvidence>){for(layer_name,source)in incoming{let layer=target.entry(layer_name.clone()).or_insert_with(||UniverseLayerEvidence::new(layer_name.clone()));for(epoch,sketch)in &source.daily{let _=layer.daily.entry(*epoch).or_insert_with(HllSketch::universe).merge(sketch);}}}

fn prune_library_epochs(library:&mut LibraryState,current:u64){let minimum=current.saturating_sub(LEXICAL_DAILY_EPOCHS_TO_KEEP.saturating_sub(1)as u64);let mut changed=false;for universe in library.universe.values_mut(){let before=universe.daily.len();universe.daily.retain(|epoch,_|*epoch>=minimum);changed|=before!=universe.daily.len();}for word in library.words.values_mut(){for layer in word.layers.values_mut(){let before=layer.daily.len();layer.daily.retain(|epoch,_|*epoch>=minimum);layer.sample.prune_before_epoch(minimum);changed|=before!=layer.daily.len();}for list in [&mut word.previous,&mut word.following]{for neighbor in list.iter_mut(){let before=neighbor.daily.len();neighbor.daily.retain(|epoch,_|*epoch>=minimum);changed|=before!=neighbor.daily.len();}list.retain(|n|!n.daily.is_empty());}}
    let before=library.phrases.len();library.phrases.retain(|_,phrase|{phrase.daily.retain(|epoch,_|*epoch>=minimum);phrase.left_occurrences.retain(|epoch,_|*epoch>=minimum);phrase.last_seen_epoch>=minimum});changed|=before!=library.phrases.len();if changed{library.manifest_dirty=true;for page in 1..LEXICAL_LIBRARY_TOTAL_SUBKEYS{library.dirty_pages.insert(page);}}
}
fn enforce_memory_retention(library:&mut LibraryState,node:[u8;32]){if library.words.len()<=LEXICAL_MAX_WORDS_IN_MEMORY{return;}let mut ranked:Vec<(WordId,[u8;32])>=library.words.keys().map(|w|(*w,xor_distance(&w.0,&node))).collect();ranked.sort_by(|a,b|b.1.cmp(&a.1));for(word,_)in ranked.into_iter().take(library.words.len()-LEXICAL_MAX_WORDS_IN_MEMORY){library.words.remove(&word);library.durable_words.remove(&word);library.dirty_pages.insert(page_for_word(&word));library.dirty_gossip.retain(|(_,w)|w!=&word);}}
fn word_is_subword_only(entry:Option<&LexicalWordEntry>,normal_layer:&str)->bool{let Some(entry)=entry else{return false;};!entry.layers.contains_key(normal_layer)&&entry.layers.keys().all(|l|l.starts_with("__subword/"))}
fn phrase_should_promote(phrase:&PhraseEvidence,current:u64)->bool{let minimum=current.saturating_sub(LEXICAL_ACTIVE_WINDOW_DAYS.saturating_sub(1)as u64);let support=super::sketches::union_hll(6,phrase.daily.range(minimum..=current).map(|(_,e)|&e.distinct_objects)).estimate();let occurrences=super::sketches::union_hll(6,phrase.daily.range(minimum..=current).map(|(_,e)|&e.distinct_occurrences)).estimate();let left=super::sketches::union_hll(6,phrase.left_occurrences.range(minimum..=current).map(|(_,e)|e)).estimate();support>=LEXICAL_PHRASE_MIN_DISTINCT_OBJECTS&&left>0.0&&(occurrences/left)>=LEXICAL_PHRASE_MIN_CONDITIONAL}

fn validate_observe_request(application_id:&str,request:&LexicalObserveRequest)->Result<(),LexicalError>{if application_id.is_empty()||application_id.len()>192{return Err(LexicalError::InvalidInput("application id is invalid".into()));}validate_library_name(&request.library_name)?;if request.layer.is_empty()||request.layer.len()>LEXICAL_MAX_LAYER_BYTES{return Err(LexicalError::InvalidInput("layer is invalid".into()));}if request.object_id.is_empty()||request.object_id.len()>LEXICAL_MAX_OBJECT_ID_BYTES{return Err(LexicalError::InvalidInput("object id is invalid".into()));}if request.field_id.is_empty()||request.field_id.len()>LEXICAL_MAX_FIELD_ID_BYTES{return Err(LexicalError::InvalidInput("field id is invalid".into()));}if request.text.as_ref().map_or(0,|t|t.len())>LEXICAL_MAX_TEXT_BYTES{return Err(LexicalError::InvalidInput("text too large".into()));}if request.pretokenized_terms.len()>LEXICAL_MAX_PRETOKENIZED_TERMS{return Err(LexicalError::InvalidInput("too many pretokenized terms".into()));}if request.text.as_deref().unwrap_or("").is_empty()&&request.pretokenized_terms.is_empty(){return Err(LexicalError::InvalidInput("text or pretokenized terms are required".into()));}Ok(())}
fn validate_library_name(name:&str)->Result<(),LexicalError>{if name.is_empty()||name.len()>LEXICAL_MAX_LIBRARY_NAME_BYTES{Err(LexicalError::InvalidInput("library name is invalid".into()))}else{Ok(())}}
pub fn derive_library_id(application_id:&str,library_name:&str)->LibraryId{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-LIBRARY-ID-V1\0");h.update(application_id.as_bytes());h.update(b"\0");h.update(library_name.as_bytes());let d=h.finalize();let mut id=[0u8;16];id.copy_from_slice(&d.as_bytes()[..16]);LibraryId(id)}
pub fn derive_phrase_id(components:&[WordId])->PhraseId{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-PHRASE-ID-V1\0");h.update(&LEXICAL_PHRASE_ID_VERSION.to_le_bytes());for c in components{h.update(&c.0);}PhraseId(*h.finalize().as_bytes())}
fn entity_fingerprint(object_id:&str)->EntityFingerprint{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-ENTITY-FP-V1\0");h.update(object_id.as_bytes());let d=h.finalize();let mut b=[0u8;6];b.copy_from_slice(&d.as_bytes()[..6]);EntityFingerprint(b)}
fn occurrence_hash(object_id:&str,generation:u64,field_id:&str,position:usize,word_id:&WordId)->u64{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-OCCURRENCE-V1\0");h.update(object_id.as_bytes());h.update(&generation.to_le_bytes());h.update(field_id.as_bytes());h.update(&(position as u64).to_le_bytes());h.update(&word_id.0);u64::from_le_bytes(h.finalize().as_bytes()[..8].try_into().unwrap())}
fn pair_occurrence_hash(object_id:&str,generation:u64,field_id:&str,left_position:usize,right_position:usize,left:&WordId,right:&WordId)->u64{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-PAIR-OCCURRENCE-V1\0");h.update(object_id.as_bytes());h.update(&generation.to_le_bytes());h.update(field_id.as_bytes());h.update(&(left_position as u64).to_le_bytes());h.update(&(right_position as u64).to_le_bytes());h.update(&left.0);h.update(&right.0);u64::from_le_bytes(h.finalize().as_bytes()[..8].try_into().unwrap())}
fn stable_hash64(domain:&[u8],bytes:&[u8])->u64{let mut h=blake3::Hasher::new();h.update(domain);h.update(bytes);u64::from_le_bytes(h.finalize().as_bytes()[..8].try_into().unwrap())}
fn node_coordinate(main_dht:&str)->[u8;32]{let mut h=blake3::Hasher::new();h.update(b"VK-LEX-NODE-COORDINATE-V1\0");h.update(main_dht.as_bytes());*h.finalize().as_bytes()}
fn xor_distance(left:&[u8;32],right:&[u8;32])->[u8;32]{let mut r=[0u8;32];for i in 0..32{r[i]=left[i]^right[i];}r}
fn epoch_for(timestamp:u64)->u64{timestamp/LEXICAL_EPOCH_SECS}
fn word_gossip_token(word_id:&WordId)->GossipIndexToken{let mut digest=[0u8;crate::gossip::GOSSIP_INDEX_TOKEN_BYTES];digest.copy_from_slice(&word_id.0[..crate::gossip::GOSSIP_INDEX_TOKEN_BYTES]);GossipIndexToken{digest}}
fn encode_minhash_bytes(signature:&[u16])->Vec<u8>{let mut b=Vec::with_capacity(signature.len()*2);for v in signature{b.extend_from_slice(&v.to_le_bytes());}b}

#[cfg(test)]mod tests{use super::*;#[test]fn entity_fingerprint_is_48_bits(){let a=entity_fingerprint("profile:alice");assert_eq!(a,entity_fingerprint("profile:alice"));assert_eq!(a.0.len(),6);}#[test]fn library_id_scoped(){assert_ne!(derive_library_id("a","default"),derive_library_id("b","default"));}#[test]fn phrase_id_ordered(){let a=WordId([1;32]);let b=WordId([2;32]);assert_ne!(derive_phrase_id(&[a,b]),derive_phrase_id(&[b,a]));}}
