//! Durable DHT layout helpers. One app/library owns one DHT. Subkey 0 is the
//! manifest and subkeys 1..63 are deterministic bounded pages.
use super::types::*;
pub fn page_for_word(word_id:&WordId)->u16{let raw=u16::from_le_bytes([word_id.0[0],word_id.0[1]])as u32;(LEXICAL_LIBRARY_PAGE_START+(raw%LEXICAL_LIBRARY_PAGE_SUBKEYS))as u16}
pub fn page_for_phrase(phrase_id:&PhraseId)->u16{let raw=u16::from_le_bytes([phrase_id.0[0],phrase_id.0[1]])as u32;(LEXICAL_LIBRARY_PAGE_START+(raw%LEXICAL_LIBRARY_PAGE_SUBKEYS))as u16}
pub fn build_membership_filter<'a,I>(words:I)->[u8;LEXICAL_MEMBERSHIP_FILTER_BYTES]where I:IntoIterator<Item=&'a WordId>{let mut f=[0u8;LEXICAL_MEMBERSHIP_FILTER_BYTES];for w in words{for p in filter_positions(w){f[p/8]|=1u8<<(p%8);}}f}
pub fn membership_filter_maybe_contains(filter:&[u8;LEXICAL_MEMBERSHIP_FILTER_BYTES],word:&WordId)->bool{filter_positions(word).into_iter().all(|p|filter[p/8]&(1u8<<(p%8))!=0)}
fn filter_positions(word:&WordId)->[usize;4]{let bits=LEXICAL_MEMBERSHIP_FILTER_BYTES*8;[u16::from_le_bytes([word.0[0],word.0[1]])as usize%bits,u16::from_le_bytes([word.0[8],word.0[9]])as usize%bits,u16::from_le_bytes([word.0[16],word.0[17]])as usize%bits,u16::from_le_bytes([word.0[24],word.0[25]])as usize%bits]}
pub fn encode_manifest(m:&LexicalLibraryManifest)->Result<Vec<u8>,String>{bincode::serialize(m).map_err(|e|e.to_string())}pub fn decode_manifest(b:&[u8])->Result<LexicalLibraryManifest,String>{bincode::deserialize(b).map_err(|e|e.to_string())}
pub fn encode_page(p:&LexicalLibraryPage)->Result<Vec<u8>,String>{let b=bincode::serialize(p).map_err(|e|e.to_string())?;if b.len()>LEXICAL_LIBRARY_MAX_PAGE_BYTES{Err(format!("lexical page {} serialized to {} bytes; maximum {}",p.page,b.len(),LEXICAL_LIBRARY_MAX_PAGE_BYTES))}else{Ok(b)}}pub fn decode_page(b:&[u8])->Result<LexicalLibraryPage,String>{bincode::deserialize(b).map_err(|e|e.to_string())}
pub fn encode_advertisements(s:&LexicalLibraryAdvertisementSet)->Result<Vec<u8>,String>{bincode::serialize(s).map_err(|e|e.to_string())}pub fn decode_advertisements(b:&[u8])->Result<LexicalLibraryAdvertisementSet,String>{let s:LexicalLibraryAdvertisementSet=bincode::deserialize(b).map_err(|e|e.to_string())?;if s.record_version!=LEXICAL_ADVERTISEMENT_RECORD_VERSION{Err(format!("unsupported lexical advertisement version {}",s.record_version))}else{Ok(s)}}
pub fn find_advertisement<'a>(set:&'a LexicalLibraryAdvertisementSet,application_id:&str,library_id:LibraryId)->Option<&'a LexicalLibraryAdvertisement>{set.libraries.iter().find(|e|e.application_id==application_id&&e.library_id==library_id)}
pub fn page_payload(library_id:LibraryId,generation:u64,page:u16,words:Vec<LexicalWordEntry>,phrases:Vec<PhraseEvidence>)->LexicalLibraryPage{LexicalLibraryPage{record_version:LEXICAL_LIBRARY_RECORD_VERSION,library_id,generation,page,words,phrases}}
